### ISSUE TITLE
NullPointerException on Falcon.drawRootToBitmap

### ISSUE THREAD

**Issue by mathroule** [jraska/Falcon#10]
When using Falcon with Spoon for instrumentation tests, this exception appears sporadically : 

The stack trace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.draw(android.graphics.Canvas)' on a null object reference
at com.jraska.falcon.Falcon.drawRootToBitmap(Falcon.java:148)
at com.jraska.falcon.Falcon.drawRootsToBitmap(Falcon.java:133)
at com.jraska.falcon.Falcon.access$100(Falcon.java:25)
at com.jraska.falcon.Falcon$1.run(Falcon.java:117)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

I could add the full Spoon trace if needed.

**Comment by jraska** [comment]
Hi, thank you for reporting this.
Can you please tell me on which device is this happening. It would be nice if you could include the whole test case and I can try to reproduce it.
Please include the Spoon trace as well.

**Comment by jraska** [comment]
Should be fixed with 0ac416. 
It will log an error when the null View in layout manager occurs. 

I'm still not sure how this can be possible and if you could provide full test case it might be handy. 

I will close the issue when I release new version.

**Comment by jraska** [comment]
Version 1.0.2 released

**Comment by mathroule** [comment]
Thanks for the fix!
