### ISSUE TITLE
Crash: onMeasure() did not set the measured dimension by calling setMeasuredDimension()

### ISSUE THREAD

**Issue by zeeshanalisayyed** [jraska/Falcon#37]
The following crash occurs on various layouts like **FrameLayout, CoordinatorLayout, RelativeLayout, TabLayout, android.support.v4.widget.NestedScrollView, AppBarLayout, Custom Views, CoordinatorLayout**, etc. The crash happens mostly while I touch/swipe on any view which is in a ListView inside ViewPager and tabs. App does not crash without using Falcon.

```
java.lang.IllegalStateException: View with id -1: android.support.design.widget.TabLayout$TabView#onMeasure() did not set the measured dimension by calling setMeasuredDimension()
    at android.view.View.measure(View.java:19199)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1723)
    at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1275)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:650)
    at android.support.design.widget.TabLayout$SlidingTabStrip.onMeasure(TabLayout.java:1859)
    at android.view.View.measure(View.java:19169)
    at android.widget.HorizontalScrollView.measureChildWithMargins(HorizontalScrollView.java:1259)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
    at android.widget.HorizontalScrollView.onMeasure(HorizontalScrollView.java:315)
    at android.support.design.widget.TabLayout.onMeasure(TabLayout.java:1030)
    at android.view.View.measure(View.java:19169)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1723)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:788)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:648)
    at android.support.design.widget.AppBarLayout.onMeasure(AppBarLayout.java:234)
    at android.view.View.measure(View.java:19169)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
    at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:719)
    at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:1008)
    at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:787)
    at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:789)
    at android.view.View.measure(View.java:19169)
    at android.widget.RelativeLayout.measureChild(RelativeLayout.java:786)
    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:560)
    at android.view.View.measure(View.java:19169)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
    at android.view.View.measure(View.java:19169)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1723)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:788)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:648)
    at android.view.View.measure(View.java:19169)
    at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1060)
    at android.view.View.measure(View.java:19169)
    at android.widget.RelativeLayout.measureChild(RelativeLayout.java:786)
    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:560)
    at android.view.View.measure(View.java:19169)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1723)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:788)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:648)
    at android.view.View.measure(View.java:19169)
    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:825)
    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:511)
    at android.view.View.measure(View.java:19169)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
    at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
    at android.view.View.measure(View.java:19169)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1723)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:788)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:648)
    at android.view.View.measure(View.java:19169)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
    at android.view.View.measure(View.java:19169)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1723)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:788)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:648)
    at android.view.View.measure(View.java:19169)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
    at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2747)
    at android.view.View.measure(View.java:19169)
    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2485)
    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1444)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1698)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1325)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6741)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:912)
    at android.view.Choreographer.doCallbacks(Choreographer.java:714)
    at android.view.Choreographer.doFrame(Choreographer.java:649)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:898)
    at android.os.Handler.handleCallback(Handler.java:815)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loop(Looper.java:207)
    at android.app.ActivityThread.main(ActivityThread.java:5769)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

Following is the same exception but on different layout, rest of the log remains same as above log:

`java.lang.IllegalStateException: View with id 2131296790: android.support.design.widget.CoordinatorLayout#onMeasure() did not set the measured dimension by calling setMeasuredDimension()`

And sometimes the crash log comes without any layout mentioned:

`java.lang.IllegalStateException: onMeasure() did not set the measured dimension by calling setMeasuredDimension()`

**Comment by zeeshanalisayyed** [comment]
Hi,

Thank you!

There is no pattern or test case I ever found to reproduce the crash, but it mostly happens when I swipe (up|down|left|right) and tap faster to navigate through items in the lists and tabs. While testing, I am hardly able to reproduce it doing the fast interaction but in live I can see many crashes related to this particular crash on crashlytics, and when I remove falcon, this crash does not occur. 

As mentioned, you can try to reproduce the crash on any app which has list of items in a list view and tabs which can be swipe-able in all directions and list item has some images which are being loaded from the internet at runtime, and you can try few fast sessions:

FrameLayout, CoordinatorLayout, RelativeLayout, TabLayout, android.support.v4.widget.NestedScrollView, AppBarLayout, Custom Views, CoordinatorLayout, etc.

**Comment by jraska** [comment]
Hello again,

I think this is more likely a problem within Android layouts, which is indirectly triggered by Falcon, because in the end everything Falcon does is calling `View.draw(Canvas canvas)`. While looking at this method docs you can find the following: 
```
...
* The view must have already done a full layout before this function is
* called.
...
```

By searching I found several people having this issue in different situations and my guess is you try to do screenshot too early within layout creation and since it happens rarely my thoughts go to concurrency issue.
_One of the ideas would be to ensure activity is resumed before taking screenshot, but this goes beyond responsibilities of Falcon so I would recommend trying it by yourself._

However this is just a guess and I cannot confirm this without runnable test, which will at least sometimes fail. Therefore no-fix so far unfortunately.

**Comment by Android355** [comment]
@zeeshanalisayyed Hi, did you manage to solve this problem?
